USE VIVERO_FENIX;

SELECT COD_CLIENTE, APELLIDO, NOMBRE
FROM CLIENTES
ORDER BY COD_CLIENTE;


SELECT COD_CLIENTE AS "CODIGO DE CLIENTE", APELLIDO, NOMBRE
FROM CLIENTES
ORDER BY APELLIDO, NOMBRE ASC;

SELECT COD_PLANTA, DESCRIPCION, PRECIO
FROM PLANTAS
ORDER BY COD_PLANTA;

SELECT DESCRIPCION AS "NOMBRE DE PLANTA", STOCK AS "STOCK ACTUAL"
FROM PLANTAS
ORDER BY DESCRIPCION;

SELECT *
FROM LOCALIDADES
ORDER BY NOMBRE;

SELECT CONCAT(NOMBRE, ' ', APELLIDO), COD_CLIENTE
FROM CLIENTES;

SELECT *, PRECIO - (PRECIO * 0.1) AS DESCUENTO
FROM PLANTAS;

SELECT *, PRECIO * STOCK AS "PRECIO TOTAL"
FROM PLANTAS;

SELECT COD_CLIENTE, NOMBRE, APELLIDO
FROM CLIENTES
WHERE DEUDOR = 'S';

SELECT *
FROM PLANTAS
WHERE STOCK > 20
ORDER BY STOCK;

SELECT *
FROM PLANTAS
WHERE NOT STOCK = 30
ORDER BY COD_PLANTA;

SELECT *
FROM FACTURAS
WHERE FECHA > '01/06/09';

SELECT *
FROM PLANTAS
WHERE STOCK < 10;

SELECT *
FROM FACTURAS
WHERE FECHA BETWEEN '01/06/08' AND '01/03/10';

SELECT *
FROM PLANTAS
WHERE PRECIO BETWEEN 20 AND 70;

SELECT DESCRIPCION, STOCK, PRECIO
FROM PLANTAS
WHERE STOCK BETWEEN 5 AND 10;

SELECT *
FROM CLIENTES
WHERE APELLIDO LIKE 'F%';

SELECT *
FROM CLIENTES
WHERE NOMBRE LIKE '%U%';

SELECT *
FROM CLIENTES
WHERE NOT (APELLIDO LIKE 'A%'
    OR APELLIDO LIKE 'B%'
    OR APELLIDO LIKE 'C%');

SELECT *
FROM CLIENTES
WHERE APELLIDO LIKE '%EZ';

SELECT *
FROM CLIENTES
WHERE APELLIDO NOT LIKE 'P%';

SELECT *
FROM CLIENTES
WHERE NOT (APELLIDO LIKE 'P%'
    OR APELLIDO LIKE 'Z%');

SELECT *
FROM CLIENTES
WHERE TELEFONO IS NULL;

SELECT APELLIDO, NOMBRE, EMAIL
FROM CLIENTES
WHERE EMAIL IS NOT NULL;

SELECT APELLIDO, NOMBRE, TELEFONO
FROM CLIENTES
WHERE TELEFONO IS NOT NULL;

SELECT *
FROM PLANTAS
WHERE DESCRIPCION LIKE 'R%'
  AND PRECIO > 7;

SELECT *
FROM PLANTAS
WHERE PRECIO < 30
   OR PRECIO > 80
ORDER BY COD_PLANTA;

SELECT APELLIDO, NOMBRE, TELEFONO, EMAIL
FROM CLIENTES
WHERE TELEFONO IS NOT NULL
   OR EMAIL IS NOT NULL;

SELECT *
FROM CLIENTES
WHERE (NOT NOMBRE LIKE 'M%' AND NOT NOMBRE LIKE 'P%')
   OR APELLIDO LIKE 'B%';

SELECT *
FROM PLANTAS
WHERE STOCK > 10
  AND STOCK < 30
ORDER BY DESCRIPCION;