DROP
DATABASE IF EXISTS STREAMING;
CREATE
DATABASE IF NOT EXISTS STREAMING;

USE
STREAMING;

CREATE TABLE PLATAFORMAS
(
    ID     INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(30)
);

CREATE TABLE DESTINOS
(
    ID     INT PRIMARY KEY AUTO_INCREMENT,
    PAIS   VARCHAR(30),
    MONEDA VARCHAR(20)
);

CREATE TABLE PRODUCTORES
(
    ID     INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(30),
    MAIL   VARCHAR(50)
);

CREATE TABLE TIPOS_EVENTO
(
    ID       INT PRIMARY KEY AUTO_INCREMENT,
    CARACTER VARCHAR(10)
);

CREATE TABLE CATEGORIAS
(
    ID     INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(30)
);

CREATE TABLE ARTISTAS
(
    ID     INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50)
);

CREATE TABLE TELEFONOS
(
    ID       INT PRIMARY KEY AUTO_INCREMENT,
    TELEFONO BIGINT
);

CREATE TABLE TIPOS_TICKET
(
    ID     INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(30)
);

CREATE TABLE EVENTOS
(
    ID            INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE        VARCHAR(40),
    ID_TIPO       INT,
    DESCRIPCCION  TEXT,
    ID_DESTINO    INT,
    ID_PLATAFORMA INT,
    LINK          VARCHAR(100),
    ID_PRODUCTOR  INT,
    CONSTRAINT `EVENTO->TIPO` FOREIGN KEY (ID_TIPO) REFERENCES TIPOS_EVENTO (ID),
    CONSTRAINT `EVENTO->DESTINO` FOREIGN KEY (ID_DESTINO) REFERENCES DESTINOS (ID),
    CONSTRAINT `EVENTO->PLATAFORMA` FOREIGN KEY (ID_PLATAFORMA) REFERENCES PLATAFORMAS (ID),
    CONSTRAINT `EVENTO->PRODUCTOR` FOREIGN KEY (ID_PRODUCTOR) REFERENCES PRODUCTORES (ID)
);

CREATE TABLE TICKETS
(
    ID             INT PRIMARY KEY AUTO_INCREMENT,
    PRECIO         INT,
    SERVICE_CHARGE INT,
    VENTA_ESPERADA INT,
    ID_EVENTO      INT,
    ID_TIPO        INT,
    CONSTRAINT `TICKET->EVENTO` FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS (ID),
    CONSTRAINT `TICKET->TIPO` FOREIGN KEY (ID_TIPO) REFERENCES TIPOS_TICKET (ID)
);

CREATE TABLE `CATEGORIA-EVENTO`
(
    ID           INT PRIMARY KEY AUTO_INCREMENT,
    ID_EVENTO    INT,
    ID_CATEGORIA INT,
    CONSTRAINT `CATEGORIA-EVENTO->EVENTO` FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS (ID),
    CONSTRAINT `CATEGORIA-EVENTO->CATEGORIA` FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS (ID)
);

CREATE TABLE `ARTISTA-EVENTO`
(
    ID         INT PRIMARY KEY AUTO_INCREMENT,
    ID_EVENTO  INT,
    ID_ARTISTA INT,
    CONSTRAINT `ARTISTA-EVENTO->EVENTO` FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS (ID),
    CONSTRAINT `ARTISTA-EVENTO->ARTISTA` FOREIGN KEY (ID_ARTISTA) REFERENCES ARTISTAS (ID)
);

CREATE TABLE `TELEFONO-PRODUCTOR`
(
    ID           INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUCTOR INT,
    ID_TELEFONO  INT,
    CONSTRAINT `TELEFONO-PRODUCTOR->PRODUCTOR` FOREIGN KEY (ID_PRODUCTOR) REFERENCES PRODUCTORES (ID),
    CONSTRAINT `TELEFONO-PRODUCTOR->TELEFONO` FOREIGN KEY (ID_TELEFONO) REFERENCES TELEFONOS (ID)
);

DESCRIBE PLATAFORMAS;
DESCRIBE DESTINOS;
DESCRIBE PRODUCTORES;
DESCRIBE TIPOS_EVENTO;
DESCRIBE CATEGORIAS;
DESCRIBE ARTISTAS;
DESCRIBE TELEFONOS;
DESCRIBE TIPOS_TICKET;
DESCRIBE EVENTOS;
DESCRIBE TICKETS;
DESCRIBE `CATEGORIA-EVENTO`;
DESCRIBE `ARTISTA-EVENTO`;
DESCRIBE `TELEFONO-PRODUCTOR`;

INSERT INTO PLATAFORMAS(NOMBRE)
VALUES ('YOUTUBE');
INSERT INTO PLATAFORMAS(NOMBRE)
VALUES ('TWITCH');
INSERT INTO PLATAFORMAS(NOMBRE)
VALUES ('VIMEO');

INSERT INTO DESTINOS(PAIS, MONEDA)
VALUES ('ARGENTINA', 'ARS');
INSERT INTO DESTINOS(PAIS, MONEDA)
VALUES ('CHILE', 'CLP');
INSERT INTO DESTINOS(PAIS, MONEDA)
VALUES ('PERU', 'PEN');
INSERT INTO DESTINOS(PAIS, MONEDA)
VALUES ('COLOMBIA', 'COP');
INSERT INTO DESTINOS(PAIS, MONEDA)
VALUES ('BOLIVIA', 'BOB');
INSERT INTO DESTINOS(PAIS, MONEDA)
VALUES ('BRASIL', 'BRL');
INSERT INTO DESTINOS(PAIS, MONEDA)
VALUES ('EEUU', 'USD');
INSERT INTO DESTINOS(PAIS, MONEDA)
VALUES ('PARAGUAY', 'PYG');

INSERT INTO PRODUCTORES (NOMBRE, MAIL)
VALUES ('DFALLACCES', 'DFALLACCES@GMAIL.COM');
INSERT INTO PRODUCTORES (NOMBRE, MAIL)
VALUES ('ALPOGO', 'ALPOGO@GMAIL.COM');
INSERT INTO PRODUCTORES (NOMBRE, MAIL)
VALUES ('GOLDENVOICE', 'GOLDENVOICE@GMAIL.COM');

INSERT INTO TIPOS_EVENTO (CARACTER)
VALUES ('PUBLICO');
INSERT INTO TIPOS_EVENTO (CARACTER)
VALUES ('PRIVADO');
INSERT INTO TIPOS_EVENTO (CARACTER)
VALUES ('MIXTO');

INSERT INTO CATEGORIAS(NOMBRE)
VALUES ('MUSICA');
INSERT INTO CATEGORIAS(NOMBRE)
VALUES ('SHOW');
INSERT INTO CATEGORIAS(NOMBRE)
VALUES ('FESTIVAL');
INSERT INTO CATEGORIAS(NOMBRE)
VALUES ('POP');
INSERT INTO CATEGORIAS(NOMBRE)
VALUES ('ROCK');
INSERT INTO CATEGORIAS(NOMBRE)
VALUES ('ATP');
INSERT INTO CATEGORIAS(NOMBRE)
VALUES ('+12');
INSERT INTO CATEGORIAS(NOMBRE)
VALUES ('+18');

INSERT INTO ARTISTAS (NOMBRE)
VALUES ('MACHINE GUN KELLY');
INSERT INTO ARTISTAS (NOMBRE)
VALUES ('DUA LIPA');
INSERT INTO ARTISTAS (NOMBRE)
VALUES ('BILLIE EILISH');
INSERT INTO ARTISTAS (NOMBRE)
VALUES ('ARCTIC MONKEYS');
INSERT INTO ARTISTAS (NOMBRE)
VALUES ('THE NEIGHBOURHOOD');
INSERT INTO ARTISTAS (NOMBRE)
VALUES ('THE WEEKND');
INSERT INTO ARTISTAS (NOMBRE)
VALUES ('BAD BUNNY');
INSERT INTO ARTISTAS (NOMBRE)
VALUES ('OLIVIA RODRIGO');

INSERT INTO TELEFONOS (TELEFONO)
VALUES (3515497968);
INSERT INTO TELEFONOS (TELEFONO)
VALUES (3515497969);
INSERT INTO TELEFONOS (TELEFONO)
VALUES (3515497970);
INSERT INTO TELEFONOS (TELEFONO)
VALUES (3515497971);
INSERT INTO TELEFONOS (TELEFONO)
VALUES (3515497972);

INSERT INTO TIPOS_TICKET (NOMBRE)
VALUES ('CAMPO');
INSERT INTO TIPOS_TICKET (NOMBRE)
VALUES ('PLATEA');
INSERT INTO TIPOS_TICKET (NOMBRE)
VALUES ('CAMPO VIP');
INSERT INTO TIPOS_TICKET (NOMBRE)
VALUES ('CAMPO VIP + M&G');

INSERT INTO EVENTOS (NOMBRE, ID_TIPO, DESCRIPCCION, ID_DESTINO, ID_PLATAFORMA, LINK, ID_PRODUCTOR)
VALUES ('LOLLAPALOOZA', 2, 'FESTIVAL DE 3 DIAS', 1, 1, 'WWW.YOUTUBE.COM/LOLLAPALOOZA', 1);
INSERT INTO EVENTOS (NOMBRE, ID_TIPO, DESCRIPCCION, ID_DESTINO, ID_PLATAFORMA, LINK, ID_PRODUCTOR)
VALUES ('SHAPE OF THE SPHERES', 2, 'TOUR DE MUSIC OF THE SPHERES', 2, 2, 'WWW.TWITCH.TV/COLDPLAY', 1);
INSERT INTO EVENTOS (NOMBRE, ID_TIPO, DESCRIPCCION, ID_DESTINO, ID_PLATAFORMA, LINK, ID_PRODUCTOR)
VALUES ('TECNOPOLIS', 1, 'MUSICA, TECNOLOGIA Y MAS', 1, 3, 'WWW.VIMEO.COM/TECNOPOLIS', 2);
INSERT INTO EVENTOS (NOMBRE, ID_TIPO, DESCRIPCCION, ID_DESTINO, ID_PLATAFORMA, LINK, ID_PRODUCTOR)
VALUES ('COACHELLA', 2, 'MUSIC FESTIVAL IN THE COACHELLA VALLEY', 7, 1, 'WWW.YOUTUBE.COM/COACHELLA', 3);
INSERT INTO EVENTOS (NOMBRE, ID_TIPO, DESCRIPCCION, ID_DESTINO, ID_PLATAFORMA, LINK, ID_PRODUCTOR)
VALUES ('MASTERS OF ROCK', 3, 'BANDAS TRIBUTO', 5, 1, 'WWW.YOUTUBE.COM/MOF', 2);

INSERT INTO TICKETS(PRECIO, SERVICE_CHARGE, VENTA_ESPERADA, ID_EVENTO, ID_TIPO)
VALUES (100, ((PRECIO * 0.15) - PRECIO), 1000, 1, 1);
INSERT INTO TICKETS(PRECIO, SERVICE_CHARGE, VENTA_ESPERADA, ID_EVENTO, ID_TIPO)
VALUES (150, ((PRECIO * 0.15) - PRECIO), 6000, 2, 2);
INSERT INTO TICKETS(PRECIO, SERVICE_CHARGE, VENTA_ESPERADA, ID_EVENTO, ID_TIPO)
VALUES (200, ((PRECIO * 0.15) - PRECIO), 5000, 3, 3);
INSERT INTO TICKETS(PRECIO, SERVICE_CHARGE, VENTA_ESPERADA, ID_EVENTO, ID_TIPO)
VALUES (100, ((PRECIO * 0.15) - PRECIO), 1000, 4, 4);
INSERT INTO TICKETS(PRECIO, SERVICE_CHARGE, VENTA_ESPERADA, ID_EVENTO, ID_TIPO)
VALUES (150, ((PRECIO * 0.15) - PRECIO), 6000, 5, 1);

INSERT INTO `CATEGORIA-EVENTO` (ID_EVENTO, ID_CATEGORIA)
values (1, 1);
INSERT INTO `CATEGORIA-EVENTO` (ID_EVENTO, ID_CATEGORIA)
values (1, 2);
INSERT INTO `CATEGORIA-EVENTO` (ID_EVENTO, ID_CATEGORIA)
values (1, 3);
INSERT INTO `CATEGORIA-EVENTO` (ID_EVENTO, ID_CATEGORIA)
values (2, 4);
INSERT INTO `CATEGORIA-EVENTO` (ID_EVENTO, ID_CATEGORIA)
values (2, 5);
INSERT INTO `CATEGORIA-EVENTO` (ID_EVENTO, ID_CATEGORIA)
values (2, 6);
INSERT INTO `CATEGORIA-EVENTO` (ID_EVENTO, ID_CATEGORIA)
values (3, 7);
INSERT INTO `CATEGORIA-EVENTO` (ID_EVENTO, ID_CATEGORIA)
values (3, 8);
INSERT INTO `CATEGORIA-EVENTO` (ID_EVENTO, ID_CATEGORIA)
values (3, 1);
INSERT INTO `CATEGORIA-EVENTO` (ID_EVENTO, ID_CATEGORIA)
values (4, 2);
INSERT INTO `CATEGORIA-EVENTO` (ID_EVENTO, ID_CATEGORIA)
values (4, 3);
INSERT INTO `CATEGORIA-EVENTO` (ID_EVENTO, ID_CATEGORIA)
values (4, 4);

INSERT INTO `ARTISTA-EVENTO` (ID_EVENTO, ID_ARTISTA)
VALUES (1, 1);
INSERT INTO `ARTISTA-EVENTO` (ID_EVENTO, ID_ARTISTA)
VALUES (1, 2);
INSERT INTO `ARTISTA-EVENTO` (ID_EVENTO, ID_ARTISTA)
VALUES (1, 3);
INSERT INTO `ARTISTA-EVENTO` (ID_EVENTO, ID_ARTISTA)
VALUES (2, 4);
INSERT INTO `ARTISTA-EVENTO` (ID_EVENTO, ID_ARTISTA)
VALUES (2, 5);
INSERT INTO `ARTISTA-EVENTO` (ID_EVENTO, ID_ARTISTA)
VALUES (2, 6);
INSERT INTO `ARTISTA-EVENTO` (ID_EVENTO, ID_ARTISTA)
VALUES (3, 7);
INSERT INTO `ARTISTA-EVENTO` (ID_EVENTO, ID_ARTISTA)
VALUES (3, 8);
INSERT INTO `ARTISTA-EVENTO` (ID_EVENTO, ID_ARTISTA)
VALUES (3, 1);
INSERT INTO `ARTISTA-EVENTO` (ID_EVENTO, ID_ARTISTA)
VALUES (4, 2);
INSERT INTO `ARTISTA-EVENTO` (ID_EVENTO, ID_ARTISTA)
VALUES (4, 3);
INSERT INTO `ARTISTA-EVENTO` (ID_EVENTO, ID_ARTISTA)
VALUES (4, 4);

INSERT INTO `TELEFONO-PRODUCTOR` (ID_PRODUCTOR, ID_TELEFONO)
VALUES (1, 1);
INSERT INTO `TELEFONO-PRODUCTOR` (ID_PRODUCTOR, ID_TELEFONO)
VALUES (1, 2);
INSERT INTO `TELEFONO-PRODUCTOR` (ID_PRODUCTOR, ID_TELEFONO)
VALUES (2, 3);
INSERT INTO `TELEFONO-PRODUCTOR` (ID_PRODUCTOR, ID_TELEFONO)
VALUES (2, 4);
INSERT INTO `TELEFONO-PRODUCTOR` (ID_PRODUCTOR, ID_TELEFONO)
VALUES (3, 5);

SELECT *
FROM PLATAFORMAS;
SELECT *
FROM DESTINOS;
SELECT *
FROM PRODUCTORES;
SELECT *
FROM TIPOS_EVENTO;
SELECT *
FROM CATEGORIAS;
SELECT *
FROM ARTISTAS;
SELECT *
FROM TELEFONOS;
SELECT *
FROM TIPOS_TICKET;
SELECT *
FROM EVENTOS;
SELECT *
FROM TICKETS;
SELECT *
FROM `CATEGORIA-EVENTO`;
SELECT *
FROM `ARTISTA-EVENTO`;
SELECT *
FROM `TELEFONO-PRODUCTOR`;
